/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/account/{accountId}/partition": {
    get: operations["GetAccountPartitions"];
    post: operations["CreateAccountPartition"];
  };
  "/account/{accountId}/partition/{accountPartitionId}/archive": {
    post: operations["ArchiveAccountPartition"];
  };
  "/account": {
    get: operations["GetAccounts"];
    post: operations["CreateAccount"];
  };
  "/account-transaction": {
    post: operations["CreateAccountTransaction"];
  };
  "/account-transaction/budget-assignment": {
    post: operations["CreateAccountTransactionFromAssignments"];
  };
  "/account-transaction/{accountTransactionId}": {
    patch: operations["EditAccountTransaction"];
  };
  "/budget-category": {
    post: operations["CreateBudgetCategory"];
  };
  "/budget-increase": {
    post: operations["CreateBudgetIncrease"];
  };
  "/month-budget": {
    post: operations["CreateMonthBudget"];
  };
  "/month-budget/{year}/{month}/duplicate": {
    post: operations["DuplicateMonthBudget"];
  };
  "/overview/account-partition/{accountPartitionId}": {
    get: operations["GetAccountPartitionOverview"];
  };
  "/overview/account-transaction/{accountId}": {
    get: operations["GetAccountTransactionOverview"];
  };
  "/overview/budget/{year}/{month}": {
    get: operations["GetBudgetOverview"];
  };
  "/settlement": {
    post: operations["CreateSettlement"];
  };
  "/transfer": {
    post: operations["CreateTransfer"];
  };
  "/transfer/savings-payment": {
    post: operations["CreateSavingsPayment"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "Ching.DTOs.AccountDTO": {
      /** Format: int32 */
      id?: number;
      name?: string | null;
    };
    "Ching.DTOs.AccountPartitionDTO": {
      /** Format: int32 */
      id?: number;
      archived?: boolean;
      budgetMonth?: components["schemas"]["Ching.DTOs.BudgetMonthDTO"];
    };
    "Ching.DTOs.BudgetMonthDTO": {
      /** Format: int32 */
      year?: number;
      /** Format: int32 */
      month?: number;
    };
    "Ching.DTOs.BudgetOverviewItemDTO": {
      /** Format: int32 */
      categoryId?: number;
      categoryName?: string | null;
      /** Format: double */
      spent?: number;
      /** Format: double */
      available?: number;
    };
    "Ching.DTOs.CreateBudgetAssignmentRequest": {
      /** Format: int32 */
      budgetCategoryId?: number;
      budgetMonth?: components["schemas"]["Ching.DTOs.BudgetMonthDTO"];
      /** Format: double */
      amount?: number;
      note?: string | null;
    };
    "Ching.DTOs.EditAccountTransactionRequest": {
      /** Format: date */
      date?: string;
      note?: string | null;
      recipient?: string | null;
      budgetAssignments?: (components["schemas"]["Ching.DTOs.CreateBudgetAssignmentRequest"])[] | null;
    };
    "Ching.DTOs.PartitionBalanceDTO": {
      /** Format: int32 */
      partitionId?: number;
      partitionName?: string | null;
      /** Format: double */
      balance?: number;
    };
    "Ching.DTOs.TransactionDTO": {
      /** Format: date */
      date?: string;
      /** Format: double */
      amount?: number;
      note?: string | null;
    };
    "Ching.DTOs.TransactionWithBalanceDTO": {
      transaction?: components["schemas"]["Ching.DTOs.TransactionDTO"];
      /** Format: double */
      balance?: number;
    };
    "Ching.Features.Account.Create+Command": {
      name?: string | null;
    };
    "Ching.Features.AccountPartition.Create+Command": {
      /** Format: int32 */
      accountId?: number;
      name?: string | null;
      budgetMonth?: components["schemas"]["Ching.DTOs.BudgetMonthDTO"];
    };
    "Ching.Features.AccountTransaction.Create+Command": {
      /** Format: int32 */
      accountPartitionId?: number;
      /** Format: date */
      date?: string;
      /** Format: double */
      amount?: number;
      recipient?: string | null;
      note?: string | null;
    };
    "Ching.Features.AccountTransaction.CreateFromBudgetAssignments+Command": {
      /** Format: int32 */
      accountPartitionId?: number;
      /** Format: date */
      date?: string;
      recipient?: string | null;
      budgetAssignments?: (components["schemas"]["Ching.Features.AccountTransaction.CreateFromBudgetAssignments+Command+BudgetAssignment"])[] | null;
    };
    "Ching.Features.AccountTransaction.CreateFromBudgetAssignments+Command+BudgetAssignment": {
      /** Format: int32 */
      budgetCategoryId?: number;
      budgetMonth?: components["schemas"]["Ching.DTOs.BudgetMonthDTO"];
      /** Format: double */
      amount?: number;
      note?: string | null;
    };
    "Ching.Features.BudgetCategory.Create+Command": {
      name?: string | null;
    };
    "Ching.Features.BudgetIncrease.Create+Command": {
      /** Format: int32 */
      budgetCategoryId?: number;
      budgetMonth?: components["schemas"]["Ching.DTOs.BudgetMonthDTO"];
      transfer?: components["schemas"]["Ching.Features.BudgetIncrease.Create+Command+TransferData"];
    };
    "Ching.Features.BudgetIncrease.Create+Command+TransferData": {
      /** Format: date */
      date?: string;
      /** Format: double */
      amount?: number;
      /** Format: int32 */
      sourcePartitionId?: number;
      /** Format: int32 */
      destinationPartitionId?: number;
    };
    "Ching.Features.MonthBudget.Create+Command": {
      /** Format: int32 */
      budgetCategoryId?: number;
      /** Format: double */
      amount?: number;
      budgetMonth?: components["schemas"]["Ching.DTOs.BudgetMonthDTO"];
    };
    "Ching.Features.Settlement.Create+Command": {
      /** Format: date */
      date?: string;
      accountTransactionIds?: (number)[] | null;
      /** Format: int32 */
      sourcePartitionId?: number;
    };
    "Ching.Features.Transfer.CreateSavingsPayment+Command": {
      /** Format: date */
      date?: string;
      /** Format: double */
      amount?: number;
      /** Format: int32 */
      sourcePartitionId?: number;
      /** Format: int32 */
      destinationPartitionId?: number;
      budgetAssignment?: components["schemas"]["Ching.Features.Transfer.CreateSavingsPayment+Command+BudgetAssignmentData"];
    };
    "Ching.Features.Transfer.CreateSavingsPayment+Command+BudgetAssignmentData": {
      /** Format: int32 */
      budgetCategoryId?: number;
      budgetMonth?: components["schemas"]["Ching.DTOs.BudgetMonthDTO"];
      /** Format: double */
      amount?: number;
      note?: string | null;
    };
    "Ching.Features.Transfer.CreateTransfer+Command": {
      /** Format: date */
      date?: string;
      /** Format: double */
      amount?: number;
      /** Format: int32 */
      sourcePartitionId?: number;
      /** Format: int32 */
      destinationPartitionId?: number;
    };
    "FluentValidation.Results.ValidationFailure": {
      propertyName?: string | null;
      errorMessage?: string | null;
      attemptedValue?: Record<string, unknown> | null;
      customState?: Record<string, unknown> | null;
      severity?: components["schemas"]["FluentValidation.Severity"];
      errorCode?: string | null;
      formattedMessagePlaceholderValues?: ({
        [key: string]: (Record<string, unknown> | null) | undefined;
      }) | null;
    };
    /**
     * Format: int32 
     * @enum {integer}
     */
    "FluentValidation.Severity": 0 | 1 | 2;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  GetAccountPartitions: {
    parameters: {
      path: {
        accountId: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": (components["schemas"]["Ching.DTOs.AccountPartitionDTO"])[];
        };
      };
    };
  };
  CreateAccountPartition: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.AccountPartition.Create+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  ArchiveAccountPartition: {
    parameters: {
      path: {
        accountPartitionId: number;
      };
    };
    responses: {
      /** @description Success */
      200: never;
    };
  };
  GetAccounts: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": (components["schemas"]["Ching.DTOs.AccountDTO"])[];
        };
      };
    };
  };
  CreateAccount: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.Account.Create+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  CreateAccountTransaction: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.AccountTransaction.Create+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  CreateAccountTransactionFromAssignments: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.AccountTransaction.CreateFromBudgetAssignments+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  EditAccountTransaction: {
    parameters: {
      path: {
        accountTransactionId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.DTOs.EditAccountTransactionRequest"];
      };
    };
    responses: {
      /** @description Success */
      200: never;
    };
  };
  CreateBudgetCategory: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.BudgetCategory.Create+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": (components["schemas"]["FluentValidation.Results.ValidationFailure"])[];
        };
      };
    };
  };
  CreateBudgetIncrease: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.BudgetIncrease.Create+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  CreateMonthBudget: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.MonthBudget.Create+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  DuplicateMonthBudget: {
    parameters: {
      path: {
        year: number;
        month: number;
      };
    };
    responses: {
      /** @description Success */
      200: never;
    };
  };
  GetAccountPartitionOverview: {
    parameters: {
      path: {
        accountPartitionId: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": (components["schemas"]["Ching.DTOs.PartitionBalanceDTO"])[];
        };
      };
    };
  };
  GetAccountTransactionOverview: {
    parameters: {
      path: {
        accountId: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": (components["schemas"]["Ching.DTOs.TransactionWithBalanceDTO"])[];
        };
      };
    };
  };
  GetBudgetOverview: {
    parameters: {
      path: {
        year: number;
        month: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": (components["schemas"]["Ching.DTOs.BudgetOverviewItemDTO"])[];
        };
      };
    };
  };
  CreateSettlement: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.Settlement.Create+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: never;
    };
  };
  CreateTransfer: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.Transfer.CreateTransfer+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  CreateSavingsPayment: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ching.Features.Transfer.CreateSavingsPayment+Command"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
}
